import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import { Inter-Bold } from 'next/font/google'
import { Inter-SemiBold } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'Untitled',
  description: 'Generated by Unframe',
}

const outfit = Outfit({ subsets: ['latin'], weight: ['500', '300', '400'] })
const inter-bold = Inter-Bold({ subsets: ['latin'] })
const inter-semibold = Inter-SemiBold({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${outfit.className} ${inter-bold.className} ${inter-semibold.className}`}>
        {children}
      </body>
    </html>
  )
}
