// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'mobile' // Variant
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "../chunks/chunk-AWHRQFVU.js";
import { className, css, fonts } from "../chunks/chunk-NMBYP4WG.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-BYV25UIZ.js";
import { Icon } from "../chunks/chunk-MJX6QVBH.js";
import "../chunks/chunk-NULYBL27.js";
import { routes } from "../chunks/chunk-RLI2ZTP2.js";

// virtual:footer/footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zk9GSsMSR2O2hn6WoAHF/8pNzC7vRvJ8vRAd2LGcz/O9U_tuvq1.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/t0weO08sUoC30RCkEL1d/5KWztqeuZBg3DpSwHrLM/g3N9ASNGG.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css4 = [
	'.framer-mWyIy .framer-styles-preset-1cg0spb:not(.rich-text-wrapper), .framer-mWyIy .framer-styles-preset-1cg0spb.rich-text-wrapper a { --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, #ffffff) /* {"name":"Primary Text"} */; --framer-link-hover-text-decoration: none; --framer-link-text-decoration: none; }',
];
var className4 = "framer-mWyIy";

// /:https://framerusercontent.com/modules/zk9GSsMSR2O2hn6WoAHF/8pNzC7vRvJ8vRAd2LGcz/O9U_tuvq1.js
var PhosphorFonts = getFonts(Icon);
var cycleOrder = ["bBoqKZmyC", "RgjwmQ9ya"];
var serializationHash = "framer-lc3gK";
var variantClassNames = {
	bBoqKZmyC: "framer-v-1pvfjmk",
	RgjwmQ9ya: "framer-v-pi75kk",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "bBoqKZmyC",
	mobile: "RgjwmQ9ya",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "bBoqKZmyC",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "bBoqKZmyC",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className, className3, className4];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.footer
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1pvfjmk",
							className5,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"bBoqKZmyC"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-6839e435-35f3-4ab3-b723-e98c27e525bc, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							...style,
						}}
						{...addPropertyOverrides(
							{
								RgjwmQ9ya: {
									"data-framer-name": "mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-7g8fj5"}
							data-framer-name={"container"}
							layoutDependency={layoutDependency}
							layoutId={"TAtUwqNey"}
						>
							<motion.div
								className={"framer-79wzoa"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"GDuEZCIeg"}
							>
								<motion.div
									className={"framer-5fqcc0"}
									data-framer-name={"Left section"}
									layoutDependency={layoutDependency}
									layoutId={"Qwo4h5ryK"}
								>
									<motion.div
										className={"framer-9m8k57"}
										data-framer-name={"Title+tagline"}
										layoutDependency={layoutDependency}
										layoutId={"kkiRt7O1f"}
									>
										<Link
											href={{
												webPageId: "augiA20Il",
											}}
											motionChild={true}
											nodeId={"e1KolLtbC"}
											openInNewTab={false}
											scopeId={"O9U_tuvq1"}
										>
											<motion.a
												className={"framer-1sbwzqv framer-irbnn9"}
												data-framer-name={"title"}
												layoutDependency={layoutDependency}
												layoutId={"e1KolLtbC"}
											>
												<Image
													background={{
														alt: "",
														fit: "fit",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) +
																64 +
																(((componentViewport?.height || 200) -
																	128 -
																	204) /
																	2 +
																	0 +
																	0) +
																0 +
																0 +
																0 +
																0 +
																0 +
																0 +
																0,
														),
														pixelHeight: 216,
														pixelWidth: 228,
														positionX: "center",
														positionY: "center",
														sizes: "40px",
														src: "https://framerusercontent.com/images/ef9qyeTSc2x0goX2BOGuWMIOk.svg?width=228&height=216",
													}}
													className={"framer-9ex6rc"}
													data-framer-name={"icon"}
													layoutDependency={layoutDependency}
													layoutId={"XCYdMrOI_"}
													{...addPropertyOverrides(
														{
															RgjwmQ9ya: {
																background: {
																	alt: "",
																	fit: "fit",
																	loading: getLoadingLazyAtYPosition(
																		(componentViewport?.y || 0) +
																			64 +
																			(((componentViewport?.height || 200) -
																				128 -
																				343.6) /
																				2 +
																				0 +
																				0) +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0 +
																			0,
																	),
																	pixelHeight: 216,
																	pixelWidth: 228,
																	positionX: "center",
																	positionY: "center",
																	sizes: "40px",
																	src: "https://framerusercontent.com/images/ef9qyeTSc2x0goX2BOGuWMIOk.svg?width=228&height=216",
																},
															},
														},
														baseVariant,
														gestureVariant,
													)}
												/>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-iwsdpc"}
													fonts={["FS;Outfit-medium"]}
													layoutDependency={layoutDependency}
													layoutId={"L7r4RaskT"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255))",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															style={{
																"--font-selector": "RlM7T3V0Zml0LW1lZGl1bQ==",
																"--framer-font-family":
																	'"Outfit", "Outfit Placeholder", sans-serif',
																"--framer-font-size": "28px",
																"--framer-font-weight": "500",
																"--framer-letter-spacing": "-0.02em",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255)))",
															}}
														>
															{"CodesDevs"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.a>
										</Link>
										<motion.div
											className={"framer-9czzrc"}
											data-framer-name={"tagline"}
											layoutDependency={layoutDependency}
											layoutId={"Fqzs8WZ_M"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1nt07qp"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"MIHQdT5Ti"}
												style={{
													"--extracted-r6o4lv":
														"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-19p2pli"}
														data-styles-preset={"vOdfG3utS"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
														}}
													>
														{
															"Your trusted partner in AI solutions, creating smarter systems for smarter businesses."
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
									<motion.div
										className={"framer-z7as9h"}
										data-framer-name={"Social media"}
										layoutDependency={layoutDependency}
										layoutId={"OHE7kzX9i"}
									>
										<Link
											href={"https://www.linkedin.com/company/codes-devs-ai/"}
											motionChild={true}
											nodeId={"gxRZSD6VQ"}
											openInNewTab={true}
											scopeId={"O9U_tuvq1"}
										>
											<motion.a
												className={"framer-xjjyjj framer-irbnn9"}
												data-framer-name={"linkedin"}
												layoutDependency={layoutDependency}
												layoutId={"gxRZSD6VQ"}
												style={{
													backgroundColor:
														"var(--token-5e82b7fb-875b-478b-b151-baffd23609a0, rgba(255, 255, 255, 0.2))",
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1adove2-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"OgHMQ_lLE-container"}
														nodeId={"OgHMQ_lLE"}
														rendersWithMotion={true}
														scopeId={"O9U_tuvq1"}
													>
														<Icon
															color={"rgb(255, 255, 255)"}
															height={"100%"}
															iconSearch={"linkedin"}
															iconSelection={"House"}
															id={"OgHMQ_lLE"}
															layoutId={"OgHMQ_lLE"}
															mirrored={false}
															selectByList={false}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
										<Link
											href={"https://x.com/Codesdevsai"}
											motionChild={true}
											nodeId={"i2nYpqNHE"}
											openInNewTab={true}
											scopeId={"O9U_tuvq1"}
										>
											<motion.a
												className={"framer-wrp73g framer-irbnn9"}
												data-framer-name={"x"}
												layoutDependency={layoutDependency}
												layoutId={"i2nYpqNHE"}
												style={{
													backgroundColor:
														"var(--token-5e82b7fb-875b-478b-b151-baffd23609a0, rgba(255, 255, 255, 0.2))",
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-s6pu69-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"vXme7XQn6-container"}
														nodeId={"vXme7XQn6"}
														rendersWithMotion={true}
														scopeId={"O9U_tuvq1"}
													>
														<Icon
															color={"rgb(255, 255, 255)"}
															height={"100%"}
															iconSearch={"x-logo"}
															iconSelection={"House"}
															id={"vXme7XQn6"}
															layoutId={"vXme7XQn6"}
															mirrored={false}
															selectByList={false}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
										<Link
											href={"https://www.instagram.com/codes.devs/"}
											motionChild={true}
											nodeId={"nGMutC2C2"}
											openInNewTab={true}
											scopeId={"O9U_tuvq1"}
										>
											<motion.a
												className={"framer-14gp7zr framer-irbnn9"}
												data-framer-name={"Instagram"}
												layoutDependency={layoutDependency}
												layoutId={"nGMutC2C2"}
												style={{
													backgroundColor:
														"var(--token-5e82b7fb-875b-478b-b151-baffd23609a0, rgba(255, 255, 255, 0.2))",
													borderBottomLeftRadius: 8,
													borderBottomRightRadius: 8,
													borderTopLeftRadius: 8,
													borderTopRightRadius: 8,
												}}
											>
												<ComponentViewportProvider>
													<SmartComponentScopedContainer
														className={"framer-1ddec7v-container"}
														isAuthoredByUser={true}
														isModuleExternal={true}
														layoutDependency={layoutDependency}
														layoutId={"U86mxiARl-container"}
														nodeId={"U86mxiARl"}
														rendersWithMotion={true}
														scopeId={"O9U_tuvq1"}
													>
														<Icon
															color={"rgb(255, 255, 255)"}
															height={"100%"}
															iconSearch={"instagram"}
															iconSelection={"House"}
															id={"U86mxiARl"}
															layoutId={"U86mxiARl"}
															mirrored={false}
															selectByList={false}
															style={{
																height: "100%",
																width: "100%",
															}}
															weight={"regular"}
															width={"100%"}
														/>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</motion.a>
										</Link>
									</motion.div>
								</motion.div>
								<motion.div
									className={"framer-1ekdqli"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"HrBeUUbaq"}
								>
									<motion.div
										className={"framer-8eb2uv"}
										data-framer-name={"Sections"}
										layoutDependency={layoutDependency}
										layoutId={"JXG_cfSEG"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1k530gz"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ZwV5gAbYQ"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1kml4oe"}
													data-styles-preset={"BzOEn0reh"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255)))",
													}}
												>
													{"Sections"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-krgcy1"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"uKAdcSKSO"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
													}}
												>
													<Link
														href={{
															hash: ":wtXL_OzbL",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"uKAdcSKSO"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Process"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-16jlk7d"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"zlpR2aXrr"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
													}}
												>
													<Link
														href={{
															hash: ":fKvIINtzq",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"zlpR2aXrr"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Services"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1l035iq"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"cpG9Q9oeY"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
													}}
												>
													<Link
														href={{
															hash: ":iaWgfKIP5",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"cpG9Q9oeY"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Benefits"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-q48ho7"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"ljL5dhOlW"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
													}}
												>
													<Link
														href={{
															hash: ":elRHUOsUh",
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"ljL5dhOlW"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={true}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Contact"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
									<motion.div
										className={"framer-101ajlz"}
										data-framer-name={"Pages"}
										layoutDependency={layoutDependency}
										layoutId={"ks_Pz2ept"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-97ffzp"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"dPvPmi92e"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1kml4oe"}
													data-styles-preset={"BzOEn0reh"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255)))",
													}}
												>
													{"Pages"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-7j7eda"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"t2mV3sOiw"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
													}}
												>
													<Link
														href={{
															webPageId: "augiA20Il",
														}}
														motionChild={true}
														nodeId={"t2mV3sOiw"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Home"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-xh5l6n"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"k0VIdnJdN"}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19jxiis"}
													data-styles-preset={"xZbbIJYTz"}
													dir={"auto"}
												>
													<Link
														href={{
															webPageId: "xEgzaVFrx",
														}}
														motionChild={true}
														nodeId={"k0VIdnJdN"}
														openInNewTab={false}
														relValues={[]}
														scopeId={"O9U_tuvq1"}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-1cg0spb"}
															data-styles-preset={"g3N9ASNGG"}
														>
															{"Blog"}
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-1ak19lv"}
							data-framer-name={"BG"}
							layoutDependency={layoutDependency}
							layoutId={"tzffQ203L"}
							style={{
								filter: "blur(50px)",
								opacity: 0.9,
								WebkitFilter: "blur(50px)",
							}}
						>
							<SVG
								className={"framer-1xu4uso"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"y2sG7dq1f"}
								opacity={0.5}
								style={{
									opacity: 0.5,
								}}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 923 328"><path d="M 459 0 C 712.499 0 918 27.534 918 61.5 C 918 95.466 712.499 123 459 123 C 205.501 123 0 95.466 0 61.5 C 0 27.534 205.501 0 459 0 Z" transform="translate(2.421 102.599) rotate(-13 459 61.5)" fill="rgba(81, 47, 235, 0.5)"></path></svg>'
								}
								svgContentId={11891251394}
								withExternalLayout={true}
							/>
						</motion.div>
					</motion.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-lc3gK.framer-irbnn9, .framer-lc3gK .framer-irbnn9 { display: block; }",
	".framer-lc3gK.framer-1pvfjmk { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; overflow: hidden; padding: 64px 40px 64px 40px; position: relative; width: 1200px; }",
	".framer-lc3gK .framer-7g8fj5 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-lc3gK .framer-79wzoa { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-lc3gK .framer-5fqcc0 { align-content: flex-start; align-items: flex-start; display: flex; flex: 3 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	".framer-lc3gK .framer-9m8k57 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-lc3gK .framer-1sbwzqv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-lc3gK .framer-9ex6rc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 38px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 40px; }",
	".framer-lc3gK .framer-iwsdpc, .framer-lc3gK .framer-1k530gz, .framer-lc3gK .framer-krgcy1, .framer-lc3gK .framer-16jlk7d, .framer-lc3gK .framer-1l035iq, .framer-lc3gK .framer-q48ho7, .framer-lc3gK .framer-97ffzp, .framer-lc3gK .framer-7j7eda, .framer-lc3gK .framer-xh5l6n { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-lc3gK .framer-9czzrc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-lc3gK .framer-1nt07qp { flex: 1 0 0px; height: auto; max-width: 350px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-lc3gK .framer-z7as9h { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-lc3gK .framer-xjjyjj, .framer-lc3gK .framer-wrp73g, .framer-lc3gK .framer-14gp7zr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 5px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-lc3gK .framer-1adove2-container, .framer-lc3gK .framer-s6pu69-container, .framer-lc3gK .framer-1ddec7v-container { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-lc3gK .framer-1ekdqli { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-lc3gK .framer-8eb2uv, .framer-lc3gK .framer-101ajlz { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; z-index: 2; }",
	".framer-lc3gK .framer-1ak19lv { bottom: 0px; flex: none; left: calc(50.00000000000002% - 923px / 2); overflow: hidden; position: absolute; top: 0px; width: 923px; z-index: 1; }",
	".framer-lc3gK .framer-1xu4uso { flex: none; height: 328px; left: calc(49.945828819068275% - 923px / 2); position: absolute; top: calc(50.00000000000002% - 328px / 2); width: 923px; }",
	".framer-lc3gK.framer-v-pi75kk.framer-1pvfjmk { width: 390px; }",
	".framer-lc3gK.framer-v-pi75kk .framer-79wzoa { flex-direction: column; gap: 25px; }",
	".framer-lc3gK.framer-v-pi75kk .framer-5fqcc0 { flex: none; gap: 15px; width: 100%; }",
	".framer-lc3gK.framer-v-pi75kk .framer-1ekdqli { flex: none; width: 100%; }",
	...css2,
	...css,
	...css3,
	...css4,
	'.framer-lc3gK[data-border="true"]::after, .framer-lc3gK [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerO9U_tuvq1 = withCSS(Component, css5, "framer-lc3gK");
var stdin_default = FramerO9U_tuvq1;
FramerO9U_tuvq1.displayName = "Footer/Footer";
FramerO9U_tuvq1.defaultProps = {
	height: 274,
	width: 1200,
};
addPropertyControls(FramerO9U_tuvq1, {
	variant: {
		options: ["bBoqKZmyC", "RgjwmQ9ya"],
		optionTitles: ["Desktop", "mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerO9U_tuvq1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Outfit",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Outfit",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/YEOHRCKDRRMJG7KXODMRI7H3TDTC7DCR/GSC37XQOTJL5UUXY7GT63Z6TK3GPURF7/3JX43FCBGINLH25MK4NSVCHCDXUSMHUE.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...PhosphorFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer/footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "RgjwmQ9ya",
	xl: "bBoqKZmyC",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var footer_default = ComponentWithRoot;
export { footer_default as default };
