// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-RLI2ZTP2.js";

// virtual:graphic
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b2Zc27KjFBnKTxwuiRz5/Z1innMncbpmv3HSoyqKF/DPbmDSLDa.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-5BMWm";
var variantClassNames = {
	NuFosMxU1: "framer-v-1pd2ywa",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "NuFosMxU1",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1pd2ywa",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"NuFosMxU1"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
					>
						<SVG
							background={{
								alt: "",
								fit: "fill",
								pixelHeight: 289,
								pixelWidth: 305,
								src: "https://framerusercontent.com/images/ef9qyeTSc2x0goX2BOGuWMIOk.svg",
							}}
							className={"framer-puitj3"}
							data-framer-name={"Graphic"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"kKDLLMK6O"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 15 15"></svg>'
							}
							svgContentId={10603006142}
							withExternalLayout={true}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-5BMWm.framer-dq83py, .framer-5BMWm .framer-dq83py { display: block; }",
	".framer-5BMWm.framer-1pd2ywa { height: 15px; overflow: visible; position: relative; width: 15px; }",
	".framer-5BMWm .framer-puitj3 { bottom: -80px; flex: none; height: 15px; position: absolute; right: -21px; width: 15px; }",
];
var FramerDPbmDSLDa = withCSS(Component, css, "framer-5BMWm");
var stdin_default = FramerDPbmDSLDa;
FramerDPbmDSLDa.displayName = "Graphic";
FramerDPbmDSLDa.defaultProps = {
	height: 15,
	width: 15,
};
addFonts(
	FramerDPbmDSLDa,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:graphic
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders GraphicFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var graphic_default = ComponentWithRoot;
export { graphic_default as default };
