// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * question1?: string // Question 1
 * answer1?: string // Answer 1
 * question2?: string // Question 2
 * answer2?: string // Answer 2
 * question3?: string // Question 3
 * answer3?: string // Answer 3
 * question4?: string // Question 4
 * answer4?: string // Answer 4
 * question5?: string // Question 5
 * answer5?: string // Answer 5
}} Props

 */
import { stdin_default } from "./chunks/chunk-DRNROSNS.js";
import "./chunks/chunk-65KVDCVG.js";
import "./chunks/chunk-MJX6QVBH.js";
import "./chunks/chunk-NULYBL27.js";
import { routes } from "./chunks/chunk-RLI2ZTP2.js";

// virtual:accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4kQJIsrL7zhOZD7E3HAI/bPKujexyoe7mTy7ZQwXE/p2GFKXSF3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var RowFonts = getFonts(stdin_default);
var serializationHash = "framer-7JvRH";
var variantClassNames = {
	yqarJseNG: "framer-v-mz0kth",
};
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 400,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	answer1,
	answer2,
	answer3,
	answer4,
	answer5,
	height,
	id,
	question1,
	question2,
	question3,
	question4,
	question5,
	width,
	...props
}) => {
	return {
		...props,
		Cex7wM3dD: question4 ?? props.Cex7wM3dD ?? "What is Framer?",
		dtRgj2l7C: question5 ?? props.dtRgj2l7C ?? "What is Framer?",
		fJGxNpSee:
			answer2 ??
			props.fJGxNpSee ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		FUmxS9SsG:
			answer3 ??
			props.FUmxS9SsG ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		j7x1ztZZn:
			answer4 ??
			props.j7x1ztZZn ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		o8grCgBRZ: question3 ?? props.o8grCgBRZ ?? "What is Framer?",
		OLAbE1hoB:
			answer5 ??
			props.OLAbE1hoB ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		PoFu0ampR: question2 ?? props.PoFu0ampR ?? "What is Framer?",
		SpwCTlbpl: question1 ?? props.SpwCTlbpl ?? "What is Framer?",
		VgfoicLnB:
			answer1 ??
			props.VgfoicLnB ??
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		SpwCTlbpl,
		VgfoicLnB,
		PoFu0ampR,
		fJGxNpSee,
		o8grCgBRZ,
		FUmxS9SsG,
		Cex7wM3dD,
		j7x1ztZZn,
		dtRgj2l7C,
		OLAbE1hoB,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "yqarJseNG",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-mz0kth",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"yqarJseNG"}
						ref={ref ?? ref1}
						style={{
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
					>
						<motion.div
							className={"framer-nlg57g"}
							data-framer-name={"BG"}
							layoutDependency={layoutDependency}
							layoutId={"Uh08kU86f"}
							style={{
								filter: "blur(50px)",
								opacity: 0.6,
								WebkitFilter: "blur(50px)",
							}}
						>
							<SVG
								className={"framer-2478eq"}
								layout={"position"}
								layoutDependency={layoutDependency}
								layoutId={"zQw6pKJ2m-shape"}
								opacity={0.5}
								style={{
									opacity: 0.5,
								}}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 923 328"><path d="M 459 0 C 712.499 0 918 27.534 918 61.5 C 918 95.466 712.499 123 459 123 C 205.501 123 0 95.466 0 61.5 C 0 27.534 205.501 0 459 0 Z" transform="translate(2.421 102.599) rotate(-13 459 61.5)" fill="rgba(81, 47, 235, 0.5)"></path></svg>'
								}
								svgContentId={11891251394}
								withExternalLayout={true}
							/>
						</motion.div>
						<ComponentViewportProvider
							height={63}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 0}
						>
							<motion.div
								className={"framer-u7b3tp-container"}
								layoutDependency={layoutDependency}
								layoutId={"t2miyULmb-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "t2miyULmb",
									layoutId: "t2miyULmb",
									style: {
										width: "100%",
									},
									T8rQFvSBR: VgfoicLnB,
									variant: "OrGQn8Vse",
									W88zB8mIG: SpwCTlbpl,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={63}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 75}
						>
							<motion.div
								className={"framer-xpkv5b-container"}
								layoutDependency={layoutDependency}
								layoutId={"ERlx909C3-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "ERlx909C3",
									layoutId: "ERlx909C3",
									style: {
										width: "100%",
									},
									T8rQFvSBR: fJGxNpSee,
									variant: "OrGQn8Vse",
									W88zB8mIG: PoFu0ampR,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={63}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 150}
						>
							<motion.div
								className={"framer-r3wlab-container"}
								layoutDependency={layoutDependency}
								layoutId={"adN7MtlJe-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "adN7MtlJe",
									layoutId: "adN7MtlJe",
									style: {
										width: "100%",
									},
									T8rQFvSBR: FUmxS9SsG,
									variant: "OrGQn8Vse",
									W88zB8mIG: o8grCgBRZ,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={63}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 225}
						>
							<motion.div
								className={"framer-8o486o-container"}
								layoutDependency={layoutDependency}
								layoutId={"oh9IVfuhG-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "oh9IVfuhG",
									layoutId: "oh9IVfuhG",
									style: {
										width: "100%",
									},
									T8rQFvSBR: j7x1ztZZn,
									variant: "OrGQn8Vse",
									W88zB8mIG: Cex7wM3dD,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={63}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0 + 300}
						>
							<motion.div
								className={"framer-1k7471a-container"}
								layoutDependency={layoutDependency}
								layoutId={"dDiNqupXn-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "dDiNqupXn",
									layoutId: "dDiNqupXn",
									style: {
										width: "100%",
									},
									T8rQFvSBR: OLAbE1hoB,
									variant: "OrGQn8Vse",
									W88zB8mIG: dtRgj2l7C,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-7JvRH.framer-olsptg, .framer-7JvRH .framer-olsptg { display: block; }",
	".framer-7JvRH.framer-mz0kth { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1000px; will-change: var(--framer-will-change-override, transform); }",
	".framer-7JvRH .framer-nlg57g { flex: none; height: 328px; left: calc(50.00000000000002% - 923px / 2); overflow: hidden; position: absolute; top: calc(50.13774104683198% - 328px / 2); width: 923px; z-index: 1; }",
	".framer-7JvRH .framer-2478eq { flex: none; height: 328px; left: calc(49.945828819068275% - 923px / 2); position: absolute; top: calc(50.00000000000002% - 328px / 2); width: 923px; }",
	".framer-7JvRH .framer-u7b3tp-container, .framer-7JvRH .framer-xpkv5b-container, .framer-7JvRH .framer-r3wlab-container, .framer-7JvRH .framer-8o486o-container, .framer-7JvRH .framer-1k7471a-container { flex: none; height: auto; position: relative; width: 100%; z-index: 2; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-7JvRH.framer-mz0kth { gap: 0px; } .framer-7JvRH.framer-mz0kth > * { margin: 0px; margin-bottom: calc(12px / 2); margin-top: calc(12px / 2); } .framer-7JvRH.framer-mz0kth > :first-child { margin-top: 0px; } .framer-7JvRH.framer-mz0kth > :last-child { margin-bottom: 0px; } }",
];
var Framerp2GFKXSF3 = withCSS(Component, css, "framer-7JvRH");
var stdin_default2 = Framerp2GFKXSF3;
Framerp2GFKXSF3.displayName = "Accordion";
Framerp2GFKXSF3.defaultProps = {
	height: 363,
	width: 1e3,
};
addPropertyControls(Framerp2GFKXSF3, {
	SpwCTlbpl: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question 1",
		type: ControlType.String,
	},
	VgfoicLnB: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		displayTextArea: true,
		title: "Answer 1",
		type: ControlType.String,
	},
	PoFu0ampR: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question 2",
		type: ControlType.String,
	},
	fJGxNpSee: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		displayTextArea: true,
		title: "Answer 2",
		type: ControlType.String,
	},
	o8grCgBRZ: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question 3",
		type: ControlType.String,
	},
	FUmxS9SsG: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		displayTextArea: true,
		title: "Answer 3",
		type: ControlType.String,
	},
	Cex7wM3dD: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question 4",
		type: ControlType.String,
	},
	j7x1ztZZn: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		displayTextArea: true,
		title: "Answer 4",
		type: ControlType.String,
	},
	dtRgj2l7C: {
		defaultValue: "What is Framer?",
		displayTextArea: true,
		title: "Question 5",
		type: ControlType.String,
	},
	OLAbE1hoB: {
		defaultValue:
			"Framer is a web builder for creative pros. Be sure to check out framer.com to learn more.\n",
		displayTextArea: true,
		title: "Answer 5",
		type: ControlType.String,
	},
});
addFonts(
	Framerp2GFKXSF3,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...RowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
