// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { routes } from "./chunks/chunk-RLI2ZTP2.js";

// virtual:icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/m3lQYrsYClMFphO1oeL4/bLOmYnVTdEfYsrdS836p/NEYnWfAdI.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-emSOD";
var variantClassNames = {
	NNxpYJvOc: "framer-v-rjhnym",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "NNxpYJvOc",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-rjhnym",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"NNxpYJvOc"}
						ref={ref ?? ref1}
						style={{
							...style,
						}}
					>
						<SVG
							background={{
								alt: "",
								fit: "fill",
								pixelHeight: 289,
								pixelWidth: 305,
								src: "https://framerusercontent.com/images/ef9qyeTSc2x0goX2BOGuWMIOk.svg",
							}}
							className={"framer-14hdp1r"}
							data-framer-name={"Graphic"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"kISTdCAiQ"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 40 38"></svg>'
							}
							svgContentId={12261726596}
							withExternalLayout={true}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-emSOD.framer-rxjh5u, .framer-emSOD .framer-rxjh5u { display: block; }",
	".framer-emSOD.framer-rjhnym { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-emSOD .framer-14hdp1r { flex: none; height: 38px; position: relative; width: 40px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-emSOD.framer-rjhnym { gap: 0px; } .framer-emSOD.framer-rjhnym > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-emSOD.framer-rjhnym > :first-child { margin-left: 0px; } .framer-emSOD.framer-rjhnym > :last-child { margin-right: 0px; } }",
];
var FramerNEYnWfAdI = withCSS(Component, css, "framer-emSOD");
var stdin_default = FramerNEYnWfAdI;
FramerNEYnWfAdI.displayName = "icon";
FramerNEYnWfAdI.defaultProps = {
	height: 38,
	width: 40,
};
addFonts(
	FramerNEYnWfAdI,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IconFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var icon_default = ComponentWithRoot;
export { icon_default as default };
