// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * name?: string // Name
 * position?: string // Position
 * content?: string // Content
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-NMBYP4WG.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-65KVDCVG.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-BYV25UIZ.js";
import { routes } from "./chunks/chunk-RLI2ZTP2.js";

// virtual:testimonial-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/eGtfjLyg6DOVXJ8kHhgI/IeFwBz1zIY3sEEXCy4bM/OmBfs0fqM.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var serializationHash = "framer-f8I3O";
var variantClassNames = {
	zacukgzQd: "framer-v-10de9mt",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 100,
};
var transition1 = {
	damping: 45,
	delay: 0,
	mass: 1,
	stiffness: 200,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	content,
	height,
	id,
	image,
	name1,
	position,
	width,
	...props
}) => {
	return {
		...props,
		lnrjkXgG0: image ??
			props.lnrjkXgG0 ?? {
				src: "https://framerusercontent.com/images/tJv6QG82Dg9NfHxZucKUlIBZmLA.jpg?scale-down-to=512",
				srcSet:
					"https://framerusercontent.com/images/tJv6QG82Dg9NfHxZucKUlIBZmLA.jpg?scale-down-to=1024 685w,https://framerusercontent.com/images/tJv6QG82Dg9NfHxZucKUlIBZmLA.jpg 857w",
			},
		rmA2Dak8S:
			content ??
			props.rmA2Dak8S ??
			'"Optimize business processes and streamline operations to significantly minimize costs and maximize overall efficiency."',
		wLhd2l9qW: position ?? props.wLhd2l9qW ?? "Managing director : Farmland",
		WVAgBk0Eg: name1 ?? props.WVAgBk0Eg ?? "Dean watson",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		lnrjkXgG0,
		WVAgBk0Eg,
		wLhd2l9qW,
		rmA2Dak8S,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "zacukgzQd",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className3, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition2}>
					<MotionDivWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__animate={{
							transition: transition1,
						}}
						__framer__animateOnce={true}
						__framer__enter={animation}
						__framer__styleAppearEffectEnabled={true}
						__framer__threshold={0.5}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-10de9mt",
							className4,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"zacukgzQd"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-6839e435-35f3-4ab3-b723-e98c27e525bc, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-c9fc1380-5d14-49ab-960e-cc3a53f6f2d0, rgba(255, 255, 255, 0.06))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
					>
						<motion.div
							className={"framer-ev7qd9"}
							data-framer-name={"Light shade"}
							layoutDependency={layoutDependency}
							layoutId={"vb3KN4cXO"}
							style={{
								backgroundColor: "rgba(81, 47, 235, 0.5)",
								borderBottomLeftRadius: 231,
								borderBottomRightRadius: 231,
								borderTopLeftRadius: 231,
								borderTopRightRadius: 231,
								filter: "blur(50px)",
								WebkitFilter: "blur(50px)",
							}}
						/>
						<motion.div
							className={"framer-17qg075"}
							data-framer-name={"Review"}
							layoutDependency={layoutDependency}
							layoutId={"NYxgFb8Xv"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-i3xron"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"loPk5Tr_v"}
								style={{
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={rmA2Dak8S}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1kml4oe"}
										data-styles-preset={"BzOEn0reh"}
									>
										{
											'"Optimize business processes and streamline operations to significantly minimize costs and maximize overall efficiency."'
										}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.div>
						<motion.div
							className={"framer-18dcipm"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"UO2f4OwFK"}
						>
							<motion.div
								className={"framer-xpzngr"}
								data-framer-name={"Icon holder"}
								layoutDependency={layoutDependency}
								layoutId={"r_q2bnbQd"}
								style={{
									backgroundColor:
										"var(--token-5e82b7fb-875b-478b-b151-baffd23609a0, rgba(255, 255, 255, 0.2))",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												20 +
												(((componentViewport?.height || 196) - 40 - 363) / 2 +
													112 +
													20) +
												92.5 +
												3,
										),
										pixelHeight: 1280,
										pixelWidth: 857,
										sizes: "40px",
										...toResponsiveImage(lnrjkXgG0),
										...{
											positionX: "center",
											positionY: "top",
										},
									}}
									className={"framer-v565g4"}
									layoutDependency={layoutDependency}
									layoutId={"Dpvga5VsG"}
									style={{
										borderBottomLeftRadius: 8,
										borderBottomRightRadius: 8,
										borderTopLeftRadius: 8,
										borderTopRightRadius: 8,
									}}
								/>
							</motion.div>
							<motion.div
								className={"framer-r91k0i"}
								data-framer-name={"Name and position"}
								layoutDependency={layoutDependency}
								layoutId={"iH335U2PK"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-3trcv6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"T2rt0QIFF"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={WVAgBk0Eg}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-ygid9r"}
											data-styles-preset={"t8V5XlRUU"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-92a1cea2-6d53-45ff-98da-32c110a8c3fc, rgb(255, 255, 255)))",
											}}
										>
											{"Dean watson"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1n255hq"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"mrAsfUJ3I"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={wLhd2l9qW}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-19p2pli"}
											data-styles-preset={"vOdfG3utS"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7)))",
											}}
										>
											{"Managing director : Farmland"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</MotionDivWithFX>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-f8I3O.framer-1oid7ju, .framer-f8I3O .framer-1oid7ju { display: block; }",
	".framer-f8I3O.framer-10de9mt { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 30px 20px 30px; position: relative; width: 353px; will-change: var(--framer-will-change-override, transform); }",
	".framer-f8I3O .framer-ev7qd9 { flex: none; height: 100px; overflow: hidden; position: absolute; right: -11px; top: -11px; width: 100px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-f8I3O .framer-17qg075 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-f8I3O .framer-i3xron, .framer-f8I3O .framer-3trcv6, .framer-f8I3O .framer-1n255hq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-f8I3O .framer-18dcipm { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-f8I3O .framer-xpzngr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 3px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-f8I3O .framer-v565g4 { flex: none; height: 40px; overflow: hidden; position: relative; width: 40px; will-change: var(--framer-will-change-override, transform); }",
	".framer-f8I3O .framer-r91k0i { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-f8I3O.framer-10de9mt, .framer-f8I3O .framer-17qg075, .framer-f8I3O .framer-18dcipm, .framer-f8I3O .framer-xpzngr, .framer-f8I3O .framer-r91k0i { gap: 0px; } .framer-f8I3O.framer-10de9mt > * { margin: 0px; margin-bottom: calc(20px / 2); margin-top: calc(20px / 2); } .framer-f8I3O.framer-10de9mt > :first-child, .framer-f8I3O .framer-17qg075 > :first-child, .framer-f8I3O .framer-r91k0i > :first-child { margin-top: 0px; } .framer-f8I3O.framer-10de9mt > :last-child, .framer-f8I3O .framer-17qg075 > :last-child, .framer-f8I3O .framer-r91k0i > :last-child { margin-bottom: 0px; } .framer-f8I3O .framer-17qg075 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-f8I3O .framer-18dcipm > *, .framer-f8I3O .framer-xpzngr > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-f8I3O .framer-18dcipm > :first-child, .framer-f8I3O .framer-xpzngr > :first-child { margin-left: 0px; } .framer-f8I3O .framer-18dcipm > :last-child, .framer-f8I3O .framer-xpzngr > :last-child { margin-right: 0px; } .framer-f8I3O .framer-r91k0i > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } }",
	...css,
	...css3,
	...css2,
	'.framer-f8I3O[data-border="true"]::after, .framer-f8I3O [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerOmBfs0fqM = withCSS(Component, css4, "framer-f8I3O");
var stdin_default = FramerOmBfs0fqM;
FramerOmBfs0fqM.displayName = "Testimonial card";
FramerOmBfs0fqM.defaultProps = {
	height: 196,
	width: 353,
};
addPropertyControls(FramerOmBfs0fqM, {
	lnrjkXgG0: {
		__defaultAssetReference:
			"data:framer/asset-reference,tJv6QG82Dg9NfHxZucKUlIBZmLA.jpg?originalFilename=business-1042706_1280.jpg&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	WVAgBk0Eg: {
		defaultValue: "Dean watson",
		displayTextArea: false,
		title: "Name",
		type: ControlType.String,
	},
	wLhd2l9qW: {
		defaultValue: "Managing director : Farmland",
		displayTextArea: false,
		title: "Position",
		type: ControlType.String,
	},
	rmA2Dak8S: {
		defaultValue:
			'"Optimize business processes and streamline operations to significantly minimize costs and maximize overall efficiency."',
		displayTextArea: true,
		title: "Content",
		type: ControlType.String,
	},
});
addFonts(
	FramerOmBfs0fqM,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:testimonial-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TestimonialCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var testimonial_card_default = ComponentWithRoot;
export { testimonial_card_default as default };
