// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 938030977dc5d310 "CodesDevs Agency Website", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * textColor?: string // Text Color
 * background?: string // Background
 * logoOpacity?: number // Logo Opacity
 * fontSize?: number // Font Size
}} Props

 */
import { routes } from "../chunks/chunk-RLI2ZTP2.js";

// virtual:elements/badge
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/m6Oj5qM6OOdcWBPhCVbA/JTafTKEyclCjfHCnJGON/BpV_0Y1_B.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-IuAt6";
var variantClassNames = {
	xY1UkxkrO: "framer-v-1lc8qgd",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	background,
	fontSize,
	height,
	id,
	logoOpacity,
	textColor,
	title,
	width,
	...props
}) => {
	return {
		...props,
		bWKfsW3Ha: background ?? props.bWKfsW3Ha ?? "rgb(13, 13, 13)",
		LZ2eCPtLx: fontSize ?? props.LZ2eCPtLx ?? 14,
		OLBJJ2ZZ2: title ?? props.OLBJJ2ZZ2 ?? "CodesDevs",
		sVlsQOR6K:
			textColor ??
			props.sVlsQOR6K ??
			"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
		zKyvF25Hr: logoOpacity ?? props.zKyvF25Hr ?? 1,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		OLBJJ2ZZ2,
		sVlsQOR6K,
		bWKfsW3Ha,
		zKyvF25Hr,
		LZ2eCPtLx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "xY1UkxkrO",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1lc8qgd",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Badge"}
						layoutDependency={layoutDependency}
						layoutId={"xY1UkxkrO"}
						ref={ref ?? ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-6839e435-35f3-4ab3-b723-e98c27e525bc, rgba(255, 255, 255, 0.1))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: bWKfsW3Ha,
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							...style,
						}}
					>
						<Image
							background={{
								alt: "",
								fit: "fit",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) +
										(8 + ((componentViewport?.height || 33) - 16 - 15) / 2),
								),
								pixelHeight: 289,
								pixelWidth: 305,
								positionX: "center",
								positionY: "center",
								src: "https://framerusercontent.com/images/ef9qyeTSc2x0goX2BOGuWMIOk.svg",
							}}
							className={"framer-1n5jjb"}
							data-framer-name={"logo holder"}
							layoutDependency={layoutDependency}
							layoutId={"oXfVRMEHL"}
							style={{
								opacity: zKyvF25Hr,
							}}
						/>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-gk8fag"}
							fonts={["FS;Outfit-light"]}
							layoutDependency={layoutDependency}
							layoutId={"yeL9I7Vwz"}
							style={{
								"--extracted-r6o4lv":
									"var(--variable-reference-sVlsQOR6K-BpV_0Y1_B)",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
								"--variable-reference-LZ2eCPtLx-BpV_0Y1_B": LZ2eCPtLx,
								"--variable-reference-sVlsQOR6K-BpV_0Y1_B": sVlsQOR6K,
							}}
							text={OLBJJ2ZZ2}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "RlM7T3V0Zml0LWxpZ2h0",
										"--framer-font-family":
											'"Outfit", "Outfit Placeholder", sans-serif',
										"--framer-font-size":
											"calc(var(--variable-reference-LZ2eCPtLx-BpV_0Y1_B) * 1px)",
										"--framer-font-weight": "300",
										"--framer-text-alignment": "center",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--variable-reference-sVlsQOR6K-BpV_0Y1_B))",
									}}
								>
									{"Radison"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IuAt6.framer-1pwso76, .framer-IuAt6 .framer-1pwso76 { display: block; }",
	".framer-IuAt6.framer-1lc8qgd { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 8px 19px 8px 19px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-IuAt6 .framer-1n5jjb { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 15px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 15px; }",
	".framer-IuAt6 .framer-gk8fag { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-IuAt6.framer-1lc8qgd, .framer-IuAt6 .framer-1n5jjb { gap: 0px; } .framer-IuAt6.framer-1lc8qgd > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-IuAt6.framer-1lc8qgd > :first-child, .framer-IuAt6 .framer-1n5jjb > :first-child { margin-left: 0px; } .framer-IuAt6.framer-1lc8qgd > :last-child, .framer-IuAt6 .framer-1n5jjb > :last-child { margin-right: 0px; } .framer-IuAt6 .framer-1n5jjb > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	'.framer-IuAt6[data-border="true"]::after, .framer-IuAt6 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerBpV_0Y1_B = withCSS(Component, css, "framer-IuAt6");
var stdin_default = FramerBpV_0Y1_B;
FramerBpV_0Y1_B.displayName = "Elements/Badge";
FramerBpV_0Y1_B.defaultProps = {
	height: 33,
	width: 130.5,
};
addPropertyControls(FramerBpV_0Y1_B, {
	OLBJJ2ZZ2: {
		defaultValue: "CodesDevs",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	sVlsQOR6K: {
		defaultValue:
			"var(--token-8c14519b-b926-46e8-8772-9a05cbede172, rgba(255, 255, 255, 0.7))",
		title: "Text Color",
		type: ControlType.Color,
	},
	bWKfsW3Ha: {
		defaultValue: "rgb(13, 13, 13)",
		title: "Background",
		type: ControlType.Color,
	},
	zKyvF25Hr: {
		defaultValue: 1,
		max: 1,
		min: 0,
		step: 0.01,
		title: "Logo Opacity",
		type: ControlType.Number,
	},
	LZ2eCPtLx: {
		defaultValue: 14,
		title: "Font Size",
		type: ControlType.Number,
	},
});
addFonts(
	FramerBpV_0Y1_B,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Outfit",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HGVZO4W7MOWSOT5FITRR2LXJL4LPEVKA/JGNFYTACJN27RPO2O5AUTRRZD4FNRJPI/W7JHARPQSG6P4YAUJKIMUM6JNAX2RFW3.woff2",
					weight: "300",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:elements/badge
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BadgeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"938030977dc5d3104727ea4c239d0fbea986c6d6fc48a106421b5fde13adcbb4"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var badge_default = ComponentWithRoot;
export { badge_default as default };
